// client-react/src/components/CastAndCrew.tsx
import React, {useState} from 'react';
import {ICredits} from '../../../client/src/app/types/people';
import useObservable from '../hooks/useObservable';
import apiService from '../services/apiService';

interface IProps {
  movieId: number;
}

export default function CastAndCrew(props: IProps) {
  const { movieId } = props;
  const [maxShown, setMaxShown] = useState<number>(10);
  const [credits, setCredits] = useState<ICredits>();

  useObservable(() => apiService.getMovieCredits(movieId), setCredits);

  const onShowAllClick = () => setMaxShown(-1);
  const castPartial = Array.from(credits?.cast || []).slice(0, maxShown);
  const showAllButtonVisible = Array.isArray(credits?.cast) && credits!.cast.length > maxShown && maxShown !== -1

  return (
    <div>
      {credits !== undefined ? (
        <>
          <h2>Cast</h2>
          <ul>
            {castPartial.map(member => (
              <li key={member.id}>
                <p>
                  <strong>{member.character || 'unspecified'}</strong> - {member.name}
                </p>
              </li>
            ))}
          </ul>
          {showAllButtonVisible && (
            <p>
              <button onClick={onShowAllClick}>
              Show all {credits?.cast!.length}
            </button>
            </p>
          )}
        </>
      ) : (<p>...</p>)}
    </div>
  );
}

// client/src/app/components/cast-and-crew/cast-and-crew.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { ICredits } from '../../types/people';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-cast-and-crew',
  templateUrl: './cast-and-crew.component.html',
  styleUrls: ['./cast-and-crew.component.scss']
})
export class CastAndCrewComponent implements OnInit {
  maxShown = 10;
  credit$: Observable<ICredits>;
  @Input() movieId: number;

  constructor(
    private api: ApiService
  ) {}

  ngOnInit(): void {
    this.credit$ = this.api.getMovieCredits(this.movieId);
  }
}

<div class="cast-and-crew-component">
  <div *ngIf="credit$ | async as credits">
    <h2>Cast</h2>
    <ul>
      <li *ngFor="let member of credits.cast.slice(0, maxShown)">
        <p>
          <strong>{{member.character || 'unspecified'}}</strong> - {{member.name}}
        </p>
      </li>
    </ul>
    <p *ngIf="credits.cast.length > maxShown && maxShown !== -1">
      <button (click)="maxShown = -1">
        Show all {{credits.cast.length}}
      </button>
    </p>
  </div>
</div>
