// client/src/app/components/discover-movies/discover-movies.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { ITopRated } from '../../types/movies';
import { ApiService } from '../../services/api.service';

type TMoviePage = Observable<ITopRated[]>;

@Component({
  selector: 'app-discover-movies',
  templateUrl: './discover-movies.component.html',
  styleUrls: ['./discover-movies.component.scss']
})
export class DiscoverMoviesComponent implements OnInit {
  moviePages: TMoviePage[] = [];
  page = 1;

  constructor(
    private api: ApiService
  ) {}

  ngOnInit(): void {
    this.download();
  }

  download() {
    this.moviePages.push(this.api.getDiscoverableMovies(this.page));
  }

  onShowMoreClick = () => {
    this.page++;
    this.download();
  }
}

<div class="discover-movies-component">
  <h2>Discover movies</h2>
  <ul>
    <li *ngFor="let moviePage$ of moviePages" class="page">
      <ul>
        <li *ngFor="let movie of moviePage$ | async" class="row">
          <a [routerLink]="['/movie', movie.id]">
            {{movie.release_date}}
            {{movie.title}}
          </a>
          <app-add-to-watchlist [movieId]="movie.id"></app-add-to-watchlist>
        </li>
      </ul>
    </li>
    <li>
      <button (click)="onShowMoreClick()">Show more</button>
    </li>
  </ul>
</div>

// client-react/src/components/DiscoverMovies.tsx
import React, {useEffect, useState} from 'react';
import {ITopRated} from '../../../client/src/app/types/movies';
import apiService from '../services/apiService';
import {Link} from 'react-router-dom';

export default function DiscoverMovies() {
  const [movies, setMovies] = useState<ITopRated[]>([]);
  const [page, setPage] = useState<number>(1);

  useEffect(() => {
    apiService.getDiscoverableMovies(page).then(data => {
      console.log(data);
      setMovies(movies.concat(data));
    });
  }, [page]);

  const onShowMoreClick = () => {
    setPage(page + 1);
  };
  return (
    <div className="discover-movies-component">
      <h2>Discover movies</h2>
      <ul>
        {movies.map(movie => (
          <li key={movie.id}>
            <Link to={`/movie/${movie.id}`}>
              {movie.release_date} {movie.title}
            </Link>
            TODO add to watchlist
          </li>
        ))}
        <li>
          <button onClick={onShowMoreClick}>Show more</button>
        </li>
      </ul>
    </div>
  );
}
