// client/src/app/components/movie-details-page/movie-details-page.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable, Subscription } from 'rxjs';
import { IDetails } from '../../types/movies';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-movie-details-page',
  templateUrl: './movie-details-page.component.html',
  styleUrls: ['./movie-details-page.component.scss']
})
export class MovieDetailsPageComponent implements OnInit, OnDestroy {
  id: number;
  title = '';
  routeChangeSubscription: Subscription;
  details$: Observable<IDetails>;

  constructor(
    private activatedRoute: ActivatedRoute,
    private api: ApiService
  ) {}

  ngOnInit(): void {
    this.routeChangeSubscription = this.activatedRoute
      .paramMap
      .subscribe(params => {
        const id = this.id = parseInt(params.get('id'), 10) || 0;
        this.title = `#${id}`;
        if (this.id) {
          this.getDetails();
        }
      });
  }

  ngOnDestroy() {
    this.routeChangeSubscription.unsubscribe();
  }

  getDetails() {
    this.details$ = this.api.getMovieDetails(this.id);
  }
}

<div class="movie-details-page-component">
  <div *ngIf="details$ | async as details">
    <h1>{{details.title}}</h1>
    <aside>{{details.overview}}</aside>
    <p *ngIf="details.vote_count > 0">
      <strong>Score:</strong>
      <span *ngFor="let i of details.vote_average | ngForNumber">⭐</span>
      <span>10 / {{details.vote_average}}</span>
    </p>
  </div>
  <div *ngIf="id">
    <app-cast-and-crew [movieId]="id"></app-cast-and-crew>
    <app-reviews [movieId]="id"></app-reviews>
  </div>
</div>

// client-react/src/components/MovieDetailsPage.tsx
/* eslint-disable jsx-a11y/accessible-emoji */
import React, {useState} from 'react';
import {useParams} from 'react-router-dom';
import useObservable from '../hooks/useObservable';
import apiService from '../services/apiService';
import {IDetails} from '../../../client/src/app/types/movies';
import {gt, num, range} from '../utils/number';
import CastAndCrew from './CastAndCrew';
import Reviews from './Reviews';

interface IPageUrlParams {
  id?: string;
}

export default function MovieDetailsPage() {
  const [details, setDetails] = useState<IDetails>();
  const urlParams = useParams() as IPageUrlParams;
  const id = parseInt(urlParams.id || '', 10) || 0;
  useObservable(() => apiService.getMovieDetails(id), setDetails, [id]);
  return (
    <div>
      {details !== undefined ? (
        <>
          <h1>{details.title}</h1>
          <aside>{details.overview}</aside>
          {gt(details.vote_count, 0) && (
            <p>
              <strong>Score:</strong>
              {range(details.vote_average).map((key) => (
                <span key={key}>⭐</span>
              ))}
              <span>
                10 / {num(details.vote_average)}
              </span>
            </p>
          )}
        </>
      ) : (
        <p>...</p>
      )}
      {id > 0 && (
        <div>
          <CastAndCrew movieId={id}/>
          <Reviews movieId={id}/>
        </div>
      )}
    </div>
  );
}
