// client-react/src/components/Reviews.tsx
import React, {useState} from 'react';
import {IReview} from '../../../client/src/app/types/movies';
import useObservable from '../hooks/useObservable';
import apiService from '../services/apiService';
import {ellipsis} from '../utils/string';

interface IProps {
  movieId: number;
}

export default function Reviews(props: IProps) {
  const { movieId } = props;
  const [reviews, setReviews] = useState<IReview[]>();
  useObservable(() => apiService.getMovieReviews(movieId), setReviews);
  return (
    <div>
      {reviews !== undefined ? (
        <>
          <h2>Reviews</h2>
          {reviews.length === 0 && (
            <p>This movie has no reviews yet.</p>
          )}
          <ul>
            {reviews.map(review => (
              <li key={review.id}>
                <h3>
                  {review.author}
                </h3>
                <p>
                  {ellipsis(review.content, 500)}
                  {review.url !== undefined && (
                    <a href={review.url} target="_blank" rel="noopener noreferrer" title="Read all">
                      <span aria-label="Read all" role="img">🔗</span>
                    </a>
                  )}
                </p>
              </li>
            ))}
          </ul>
        </>
      ) : (<p>...</p>)}
    </div>
  );
}

// client/src/app/components/reviews/reviews.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { IReview } from '../../types/movies';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-reviews',
  templateUrl: './reviews.component.html',
  styleUrls: ['./reviews.component.scss']
})
export class ReviewsComponent implements OnInit {
  reviews$: Observable<IReview[]>;
  @Input() movieId: number;

  constructor(
    public api: ApiService
  ) {}

  ngOnInit(): void {
    this.reviews$ = this.api.getReviews(this.movieId);
  }
}

<div class="reviews-component">
  <h2>Reviews</h2>
  <p *ngIf="reviews$">This movie has no reviews yet.</p>
  <ul>
    <li *ngFor="let review of reviews$ | async">
      <h3>
        {{review.author}}
      </h3>
      <p>
        {{review.content | textEllipsis:[500]}}
        <a href="{{review.url}}" *ngIf="review.url" target="_blank" title="Read all">🔗</a>
      </p>
    </li>
  </ul>
</div>
