// client-react/src/components/AddToWatchlist.tsx
import React, {useEffect, useState} from 'react';
import watchlistService from '../services/watchlistService';
import useObservable from '../hooks/useObservable';

interface IProps {
  movieId?: number
}

export default function AddToWatchlist(props: IProps) {
  const movieId = props.movieId || 0;
  const [isAdded, setIsAdded] = useState<boolean>(false);
  const [list, setList] = useState<number[]>([]);

  useObservable<number[]>(watchlistService.list$, setList);
  useEffect(() => { setIsAdded(list.includes(movieId)); }, [list, movieId]);

  const onClick = () => {
    if (isAdded) {
      watchlistService.removeFromWatchlist(movieId);
    } else {
      watchlistService.addToWatchlist(movieId);
    }
  };
  return (
    <div>
      <button onClick={onClick}>
        {isAdded ? 'Remove from watchlist' : 'Add to watchlist'}
      </button>
    </div>
  );
}

// client/src/app/components/add-to-watchlist/add-to-watchlist.component.ts
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { WatchlistService } from '../../services/watchlist.service';

@Component({
  selector: 'app-add-to-watchlist',
  templateUrl: './add-to-watchlist.component.html',
  styleUrls: ['./add-to-watchlist.component.scss']
})
export class AddToWatchlistComponent implements OnInit, OnDestroy {
  @Input() movieId: number;
  unregisterListener: () => void;
  isAdded = false;

  constructor(
    private watchlistService: WatchlistService
  ) { }

  ngOnInit() {
    this.unregisterListener = this.watchlistService
      .registerListener(this.movieId, (state) => this.isAdded = state);
  }

  ngOnDestroy() {
    this.unregisterListener();
  }

  onClick = () => {
    if (this.isAdded) {
      this.watchlistService.removeFromWatchlist(this.movieId);
    } else {
      this.watchlistService.addToWatchlist(this.movieId);
    }
  }
}

<div class="add-to-watchlist">
  <button (click)="onClick()">
    {{isAdded ? 'Remove from watchlist' : 'Add to watchlist'}}
  </button>
</div>
