// client-react/src/components/WatchlistPage.tsx
import React from 'react';
import watchlistService from '../services/watchlistService';

export default function WatchlistPage() {
  const onClearWatchlistClick = () => watchlistService.reset();
  return (
    <div>
      <h1>NYI :(</h1>
      <p>
        Technically the user <em>can</em> save a watchlist...
      </p>
      <p>
        <button onClick={onClearWatchlistClick}>Clear my watchlist</button>
      </p>
    </div>
  );
}

// client/src/app/components/watchlist-page/watchlist-page.component.ts
import { Component } from '@angular/core';
import { WatchlistService } from '../../services/watchlist.service';

@Component({
  selector: 'app-watchlist-page',
  templateUrl: './watchlist-page.component.html',
  styleUrls: ['./watchlist-page.component.scss']
})
export class WatchlistPageComponent {
  constructor(
    private watchlistService: WatchlistService
  ) {}

  onClearWatchlistClick() {
    this.watchlistService.reset();
  }
}

<div class="watchlist-page-component">
  <h1>NYI :(</h1>
  <p>
    Technically the user <em>can</em> save a watchlist...
  </p>
  <p>
    <button (click)="onClearWatchlistClick()">Clear my watchlist</button>
  </p>
</div>
